### PR TITLE
[PG15] Feature/replicas

### PR DESCRIPTION
**Pull request by MMeent**
See https://github.com/neondatabase/neon/pull/3793

### CODE REVIEW

**Review by knizhnik — APPROVED** [review]

**Comment by alexanderlaw** [comment]
@MMeent , sorry for bumping the old issue, but I've stumbled upon a dubious thing introduced here.
Namely, this in XLogWaitForReplayOf(), e.g., in postgres-v15:
```c
	timeout = ConditionVariableTimedSleep(&XLogRecoveryCtl->replayProgressCV,
										  10000000, /* 10 seconds */
										  WAIT_EVENT_RECOVERY_WAL_STREAM);
```
Does 10000000 really mean 10 seconds for that function?

I'm seeing inside that function:
```c
            cur_timeout = timeout - (long) INSTR_TIME_GET_MILLISEC(cur_time);
```

Maybe the value passed is incorrect?

(I have discovered this when noticed that that sleep lasts for more than 5 minutes.)

**Comment by MMeent** [comment]
Yep, seems like it indeed is off by factor 1000.

**Comment by MMeent** [comment]
I've created PRs for the issue for all PG versions and the Neon repo, so this won't remain an issue for much longer. Thank you for reporting this issue!

**Comment by alexanderlaw** [comment]
Thank you for paying attention to this!

**Pull request merged**
